CREATE TABLE IF NOT EXISTS accounts(
id UUID PRIMARY KEY,
name text NOT NULL,
cpf text UNIQUE NOT NULL,
secret text UNIQUE NOT NULL,
balance int NOT NULL,
createdAt TIMESTAMP WITH TIME ZONE NOT NULL
);